version: "3.8"

volumes:
  jls:
networks: 
  jls-network:
      driver: bridge

services:
  msmtpd:
    container_name: jls_msmtpd
    image: crazymax/msmtpd:latest
    restart: always
    expose: 
      - 2500
    networks: 
      jls-network:
        aliases: 
          - msmtpd
    env_file:
      - "./msmtpd.env"
      - "./msmtpd-passwd.env"
    
  jls:
    container_name: jls
    image: crazymax/jetbrains-license-server:latest
    depends_on:
      - msmtpd
    ports:
      - 8000:8000
    networks: 
      jls-network:
    volumes:
      - jls:/data
    env_file:
      - ./jls.env
    restart: always
