version: '3'
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    network_mode: bridge
    environment:
      - HOST_CONTAINERNAME=prowlarr
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://[IP]:[PORT:9696]/system/status
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-logo.png
    ports:
      - 9696:9696/tcp
    volumes:
      - ${DEFAULT_CONFIG_DIR}/prowlarr:/config:rw
