version: '3.9'
services:
  ddns:
    container_name: cloudflare-ddns
    image: timothyjmiller/cloudflare-ddns:latest
    restart: unless-stopped
    
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.icon=https://github.com/kilrah/unraid-docker-templates/raw/main/icons/cloudflare-ddns-config.png

    network_mode: bridge
    environment:
      - PUID=99
      - PGID=100
      - TZ=Asia/Shanghai
      - HOST_OS=Unraid
      - HOST_HOSTNAME=unraid
      - HOST_CONTAINERNAME=cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./cloudflare-ddns/config.json:/config.json
  vpn:
  
    image: deasmi/unraid-tailscale:latest
    container_name: Tailscale
    restart: unless-stopped

    network_mode: host
    privileged: true
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=99
      - PGID=100
      - TZ=Asia/Shanghai
      - HOST_OS=Unraid
      - HOST_HOSTNAME=unraid
      - HOST_CONTAINERNAME=cloudflare-ddns
      - ENABLE_DOWNLOADS='TRUE'
      - UP_FLAGS=--advertise-exit-node --advertise-routes=192.168.10.0/24
    volumes:
      - ./tailscale:/state:rw
      - ./tailscale/downloads:/downloads:rw
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.icon=https://raw.githubusercontent.com/deasmi/unraid-tailscale/master/logo.png
  
  sync:
    image: tickstep/aliyunpan-sync:latest
    container_name: aliyunpan-sync
    restart: unless-stopped

    volumes:
      - ./aliyunpan-sync:/home/app/config
      - /mnt/user/data:/home/app/data:rw
    environment:
      - PUID=99
      - PGID=100
      - TZ=Asia/Shanghai
      - HOST_OS=Unraid
      - HOST_HOSTNAME=unraid
      - HOST_CONTAINERNAME=aliyunpan-sync
      # refresh token
      - ALIYUNPAN_REFRESH_TOKEN=aefd8c7315b74844bbf330aabbc640d8
      # 上传下载链接类型：1-默认 2-阿里ECS环境
      - ALIYUNPAN_TRANSFER_URL_TYPE=1
      # 下载文件并发数
      - ALIYUNPAN_DOWNLOAD_PARALLEL=2
      # 上传文件并发数
      - ALIYUNPAN_UPLOAD_PARALLEL=2
      # 下载数据块大小，单位为KB，默认为10240KB，建议范围1024KB~10240KB
      - ALIYUNPAN_DOWNLOAD_BLOCK_SIZE=10240
      # 上传数据块大小，单位为KB，默认为10240KB，建议范围1024KB~10240KB
      - ALIYUNPAN_UPLOAD_BLOCK_SIZE=10240
      # 指定网盘文件夹作为备份目录，不要指定根目录
      - ALIYUNPAN_PAN_DIR=/nas
      # 备份模式：upload(备份本地文件到云盘), download(备份云盘文件到本地), sync(双向同步备份)
      - ALIYUNPAN_SYNC_MODE=sync
      # 优先级，只对双向同步备份模式有效。选项支持三种: time-时间优先，local-本地优先，pan-网盘优先
      - ALIYUNPAN_SYNC_PRIORITY=time
      # 是否显示文件备份过程日志，true-显示，false-不显示
      - ALIYUNPAN_SYNC_LOG=true
      # 本地文件修改检测延迟间隔，单位秒。如果本地文件会被频繁修改，例如录制视频文件，配置好该时间可以避免上传未录制好的文件
      - ALIYUNPAN_LOCAL_DELAY_TIME=15
      # 任务步骤, 支持两种: scan(只扫描并建立同步数据库),sync(正常启动同步任务)
      - ALIYUNPAN_TASK_STEP=sync
      # 登录设备的ID，默认为空，程序会自动生成一个ID

