version: '3'
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: bridge
    environment:
      - TZ=Asia/Shanghai
      - HOST_OS=Unraid
      - HOST_HOSTNAME=unraid
      - HOST_CONTAINERNAME=prowlarr
      - PUID=99
      - PGID=100
      - UMASK=022
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://[IP]:[PORT:9696]/system/status
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-logo.png
    ports:
      - 9696:9696/tcp
    volumes:
      - ./config/prowlarr:/config:rw
