version: '3'
services:
  mysql5:
    container_name: mysql5
    build:
      dockerfile: Dockerfile
      context: ./mysql5
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - Mysql5Data:/var/lib/mysql
      - ./mysql5/log:/var/log/mysql
  redis:
    container_name: redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    ports:
      - 6379:6379
    volumes:
      - RedisData:/data


volumes:
  Mysql5Data:
  RedisData:
  