version: "3"

services:
  mysql5:
    image: mysql:5
    restart: "no"
    container_name: mysql-db-5.x
    labels:
      space.xiayang.description: "This is for the local mysql sercice."
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./mysql5/data:/var/lib/mysql:rw
      - ./mysql5/conf.d:/etc/mysql/conf.d:rw
      - ./mysql5/logs:/var/log/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD="password"
      - TZ="Asia/Shanghai"
    command:
      --max_allowed_packet=128M
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
  
  redis:
    image: redis:alpine
    container_name: redis-db
    labels:
      space.xiayang.description: "This is for the local redis sercice."
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./redis/data:/data:rw
      - ./redis:/usr/local/etc/redis:rw