version: '3'
services:
  mysql:
    container_name: mysql-db
    image: 'mysql:5'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    volumes:
      - './data:/var/lib/mysql'
      - './conf:/etc/mysql/conf.d'
      - './log:/var/log/mysql'
