version: '3'
services:
  mysql:
    container_name: mysql-db
    image: 'mysql:5'
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    volumes:
      - './mysql/data:/var/lib/mysql'
      - './mysql/conf:/etc/mysql/conf.d'
      - './mysql/log:/var/log/mysql'
