version: '3.3'
services:
  verdaccio:
    container_name: verdaccio
    image: verdaccio/verdaccio
    environment:
      - VERDACCIO_PORT=4873
    volumes:
      - './storage:/verdaccio/storage'
    ports:
      - '4873:4873'
