version: "3"

services:
  main:
    container_name: nginx-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports: 
      - 80:80
      - 81:81
      - 443:443
    environment:
      DISABLE_IPV6: true
      DB_SQLITE_FILE: /data/database.sqlite
    volumes: 
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      