version: '3'
services:
  redis:
    container_name: redis-db
    image: redis:6-alpine
    restart: always
    command: redis-server --appendonly yes    
    ports:
      - 6379:6379
    volumes:
      - ./data:/data

